name: Clippy checks

on:
  push:
    branches:
      - develop

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: nightly

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install dependencies
      run: make install-deps-ubuntu-openslide3
    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: clippy, rustfmt
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all --fix --all-targets --allow-dirty
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --workspace --verbose
    - name: Commit and push changes
      id: cpr
      continue-on-error: true
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.SCOPED_GITHUB_TOKEN }}
        commit-message: Run clippy on the code base
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: '[Clippy] Code maintenance'
        body: |
          🤖 This is an automatic PR 🤖
          Clippy suggests the following changes
        labels: not_in_changelog
        branch: auto/clippy
        base: develop
    - name: Check outputs
      if: ${{ success() }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
