name: Release

on:
  workflow_dispatch: # only for release on develop branch
  push:
    branches:
      - main
      - rc
      - experimental
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # Semantic release need use SCOPED_GITHUB_TOKEN to create release

      - name: Install semantic-release-cargo
        uses: EricCrosson/install-github-release-binary@v2
        with:
          targets: semantic-release-cargo/semantic-release-cargo@v2.2.30

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.SCOPED_GITHUB_TOKEN }}
        with:
          semantic_version: 22.0.6
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@7.0.2
            @saithodev/semantic-release-backmerge@3.2.1
